In [6]:
import numpy as np


In [7]:
a=np.arange(10, 49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [8]:
"""Matrix 3x3"""
a=np.array([
    [3, 5, 6],
    [7, 8, 0], 
    [1, 2, 4]
])
a


array([[3, 5, 6],
       [7, 8, 0],
       [1, 2, 4]])

In [9]:
"""Create a 3x3 identity matrix"""
identity_matrix = np.identity(3)

identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
"""Create a 3x3x3 array with random values"""
random=np.random.random((3,3,3))
random

array([[[0.46789398, 0.17475735, 0.61931011],
        [0.92410781, 0.08725376, 0.27438889],
        [0.80369156, 0.28338455, 0.63341588]],

       [[0.39704853, 0.20495859, 0.74692808],
        [0.78394264, 0.7962399 , 0.02619459],
        [0.75103952, 0.93196007, 0.0495909 ]],

       [[0.50851332, 0.71906388, 0.42990584],
        [0.5599415 , 0.08104365, 0.75923084],
        [0.57450036, 0.06877712, 0.72232615]]])

In [11]:
'''Create a 10x10 array with random values and find the minimum and maximum values.'''
random=np.random.random((10, 10))
max_value=np.max(random)
min_value=np.min(random)
print(f'max_value is {max_value}, min_value is {min_value}')

max_value is 0.9970567946964161, min_value is 0.0203753405804602


In [12]:
"""Create a random vector of size 30 and find the mean value."""
a=np.arange(30, 89, 2)
mean_value = np.mean(a)
print(f'mean_value in {mean_value}')

mean_value in 59.0


In [13]:
'''Normalize a 5x5 random matrix'''

random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))
print(f'normalized_matrix is  {normalized_matrix}')


normalized_matrix is  [[0.97594035 0.1031764  0.75596828 1.         0.20541731]
 [0.71509157 0.42293785 0.43328725 0.77821593 0.4083773 ]
 [0.9274298  0.72012708 0.47202098 0.92526536 0.3362427 ]
 [0.3472986  0.8649937  0.57389185 0.50427919 0.27398956]
 [0.4467339  0.9621227  0.         0.78187483 0.93616498]]


In [14]:
'''Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).'''
A=np.random.random((5, 3))
B= np.random.random((3, 2))
C=np.dot(A, B)
print(f'Multiply two matrix: {C}')

Multiply two matrix: [[0.57611195 0.8722221 ]
 [0.50176285 0.63818683]
 [0.65352088 1.04230779]
 [0.39144167 1.03097232]
 [0.48582549 0.92549532]]


In [16]:
"""Create two 3x3 matrices and compute their dot product."""
A=([
    [2, 3, 5],
    [5, 1, 7],
    [9, 8, 6]
])
B=([
    [1, 2, 3],
    [3, 4, 5],
    [5, 1, 7]
])
multiply=np.dot(A, B)
print(multiply)

[[ 36  21  56]
 [ 43  21  69]
 [ 63  56 109]]


In [24]:
'''Given a 4x4 matrix, find its transpose.'''
matrix=np.random.rand(4,4)
matrix_transponse=np.transpose(matrix)
print(matrix)
print(f' this matrix transponse   ')
print(matrix_transponse)

[[0.37058587 0.27594516 0.02892735 0.85966013]
 [0.99416415 0.09925521 0.66042254 0.47747146]
 [0.32712546 0.31992715 0.223232   0.73773953]
 [0.18136898 0.60379684 0.12841261 0.17010165]]
 this matrix transponse   
[[0.37058587 0.99416415 0.32712546 0.18136898]
 [0.27594516 0.09925521 0.31992715 0.60379684]
 [0.02892735 0.66042254 0.223232   0.12841261]
 [0.85966013 0.47747146 0.73773953 0.17010165]]


In [31]:
'''Create a 3x3 matrix and calculate its determinant.'''
matrix=np.random.rand(3,3)
determinant=np.linalg.det(matrix)
print(f'{matrix} determinat equal {determinant}')

[[0.0296911  0.76213501 0.03879068]
 [0.59795535 0.91820111 0.23469532]
 [0.15570048 0.67081038 0.11206449]] determinat equal -0.014825738299240157


In [32]:
'''Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).'''
A=np.random.random((3, 4))
B= np.random.random((4, 3))
C=np.dot(A, B)
print(f'A equal{A}')
print(f'B equal{B}')
print(f'C equal{C}')

A equal[[0.91380267 0.69882965 0.4922445  0.11416892]
 [0.44117586 0.26630439 0.11054404 0.12728349]
 [0.49222782 0.52108686 0.35720382 0.88256941]]
B equal[[0.06243322 0.58632074 0.62542251]
 [0.36091886 0.05010873 0.59554838]
 [0.20652308 0.48390482 0.40021827]
 [0.44030802 0.1932414  0.03562435]]
C equal[[0.46120179 0.83106058 1.18877206]
 [0.20253215 0.35010397 0.4832946 ]
 [0.68117467 0.65811599 0.79258325]]


<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\user\AppData\Local\Temp\ipykernel_108204\2616956178.py:1: SyntaxWarning: invalid escape sequence '\c'
  '''Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).'''


In [40]:
'''Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.'''
matrix=np.random.random((3,3))
vector=np.array([
    [3], 
    [2],
    [5]  
      ])
multiply=np.dot(matrix, vector)
print(f' {matrix}, and {vector} multiple equal')
print(multiply)

 [[0.73403178 0.38288578 0.65988853]
 [0.28714959 0.93590727 0.15247612]
 [0.21573303 0.09611601 0.6997032 ]], and [[3]
 [2]
 [5]] multiple equal
[[6.26730954]
 [3.4956439 ]
 [4.33794709]]


In [42]:
'''Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.'''
A=np.array([
    [1, 2, 3],
    [3, 4, 5],
    [5, 1, 7]
])

b=np.array([
    [3], 
    [2],
    [5]  
      ])
x = np.linalg.solve(A, b)
print(x)


[[-1.85]
 [-0.8 ]
 [ 2.15]]


In [44]:
'''Given a 5x5 matrix, find the row-wise and column-wise sums.'''
matrix=np.random.random((5,5))
row_sums = np.sum(matrix, axis=1)
column_sums = np.sum(matrix, axis=0)
print("Row-wise sums:", row_sums)
print("Column-wise sums:", column_sums)

Row-wise sums: [2.48947311 2.32224077 2.45181412 3.07095114 2.19143451]
Column-wise sums: [2.31236397 2.37506378 3.08693163 2.40692244 2.34463183]
